Raise a tink.TinkError when hybrid encryption is called without a primary key.
Currently, a "AttributeError: 'NoneType' object has no attribute 'identifier'" is raised, which may be confusing to the user.

I added some tests that load the same JSON keysets with and without primary key.

PiperOrigin-RevId: 439511856