Replacing text option with JSON in Tinkey.
Exception: key templates are still text because they have comments
which are not supported in JSON.

Change-Id: Ifb00c32d0159beaf0391fa6a324e563254f8059a
ORIGINAL_AUTHOR=Thai Duong <thaidn@google.com>
GitOrigin-RevId: ec95e3fa65912e89426a49129d9fd19cc108276f